antonspro/about/urls.py
from django.conf.urls import url
from . import views


app_name='about'

urlpatterns= [
    url(r'aboutSu$',views.SuAbout.as_view(),name='aboutsu'),
    url(r'^general/$',views.GenAbout.as_view(),name='general'),
    url(r'^planet/$',views.PlanetAbout.as_view(),name='aboutpe')
]

antonspro/antonspro/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Home/$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^$',views.MasterPage.as_view(),name='masterpage'),
    url(r'^sudoku/',include('sudoku.urls',namespace='sudoku')),
    url(r'^about/',include('about.urls',namespace='about')),
    url(r'^experiment/',include('experiment.urls',namespace='experiment')),
    url(r'^buy/$',views.BuyPage.as_view(),name='buy'),
    url(r'^magicclub/',include('magicclub.urls',namespace='magicclub')),
    url(r'^adventure/',include('adventure.urls',namespace='adventure')),
]

antonspro/experiment/urls.py
from . import views
from django.conf.urls import url

app_name='experiment'

urlpatterns= [
    url(r'experiment/$',views.FirstView.as_view(),name='myrooms'),
    url(r'posts/in/(?P<slug>[-\w]+)/(?P<elnamo>[-\S]+)$',views.SingleGroup.as_view(),name='single1'),
    url(r'^$',views.ListGroups.as_view(),name='all1'),
    url(r'^new/$',views.CreateGroup.as_view(),name='create1'),
    url(r'join/(?P<slug>[-\S]+)/(?P<elnamo>[-\S]+)$',views.JoinGroup.as_view(),name='join1'),
    url(r'leave/(?P<slug>[-\S]+)/(?P<elnamo>[-\S]+)$',views.LeaveGroup.as_view(),name='leave1'),
    url(r'bjudge/(?P<slug>[-\w]+)/(?P<elnamo>[-\S]+)$',views.BecomeJudge.as_view(),name='bjudge1'),
    url(r'unjudge/(?P<slug>[-\w]+)/(?P<elnamo>[-\S]+)$',views.UnJudge.as_view(),name='unjudge1'),
    # url(r'fill/$',views.FillBoard.as_view(),name='FillBoard'),
    # url(r'^search/',views.solution.as_view(),name='solution')
]

antonspro/experiment/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django import template
register = template.Library()

# groups models.py file
# Create your models here.
from django.contrib.auth import get_user_model
User= get_user_model()

# Create your models here.

class EGroup(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html= models.TextField(editable=False,default='',blank=True)
    members1= models.ManyToManyField(User,through='InGroup')
    judge=models.ManyToManyField(User,through='IsJudge',related_name='judges')
    goldinroom= models.DecimalField(verbose_name='goldinroom',default=0,max_digits=6,decimal_places=2,)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug= slugify(self.name)

        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('experiment:single1',kwargs={'slug':self.slug,'elnamo':self.slug})

    class Meta:
        ordering= ['name']

class InGroup(models.Model):
    group= models.ForeignKey(EGroup,related_name='membership',on_delete=models.CASCADE)
    user= models.ForeignKey(User,related_name='user_group',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

class IsJudge(models.Model):
    courtroom= models.ForeignKey(EGroup,related_name='courtroomjudge',on_delete=models.CASCADE)
    judge1= models.ForeignKey(User,related_name='judge_group',on_delete=models.CASCADE)

    def __str__(self):
        return self.judge1.username

    class Meta:
        unique_together = ('courtroom','judge1')

antonspro/experiment/forms.py
from django import forms
from . import views
from accounts.models import Account
from django.shortcuts import render
from django.db import models


class GoldForm(forms.Form):
    givegold= forms.DecimalField(max_value=None,min_value=0,max_digits=6,decimal_places=2)

class JudgeGold(forms.Form):
    jgold= forms.DecimalField(max_value=None,min_value=0,max_digits=6,decimal_places=2,initial=0,label='',required='False')

antonspro/experiment/views.py
from django.shortcuts import render
from django.db import models
from django.views.generic import TemplateView
from django.views import generic
from . import models
from experiment.models import EGroup,InGroup,IsJudge
from .forms import GoldForm,JudgeGold
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                    PermissionRequiredMixin)
from django.shortcuts import get_object_or_404
from accounts.models import Account
from django.contrib import messages
from django.db import IntegrityError
from django.urls import reverse
from django.contrib.auth import get_user_model
User= get_user_model()

# Create your views here.

class FirstView(generic.ListView):
    model = models.InGroup
    template_name = 'experiment/first.html'





class CreateGroup(generic.CreateView):
    fields=('name','description')
    model= EGroup

class SingleGroup(generic.DetailView):
    template_name = 'experiment/egroup_detail.html'
    model=EGroup


    def get(self, request, slug,elnamo):
        model=EGroup
        group= get_object_or_404(EGroup,slug=self.kwargs.get('slug'))
        form2 = GoldForm()
        form3= JudgeGold()

        args = {'form':form2,'name':group,'form3':form3}
        return render(request,self.template_name,args)


    def post(self, request,slug,elnamo):
        form = GoldForm(request.POST)
        form3 = JudgeGold(request.POST)
        group= get_object_or_404(EGroup,slug=self.kwargs.get('slug'))
        if form.is_valid():
            name = request.user
            gold = form.cleaned_data["givegold"]
            if name.gold >= gold:
                name.gold=name.gold-gold
                group.goldinroom=group.goldinroom+gold
                name.save()
                group.save()

        if form3.is_valid():
            person=Account.objects.get(username=request.POST.get('name'))
            gold = form3.cleaned_data["jgold"]
            group= get_object_or_404(EGroup,slug=self.kwargs.get('slug'))
            if group.goldinroom >= gold:
                person.gold=person.gold+gold
                group.goldinroom=group.goldinroom-gold
                group.save()
                person.save()

        args = {'form':form,'name':group,'form3':form3}
        return render(request, self.template_name,args)



class ListGroups(generic.ListView):
    model = EGroup

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('experiment:single1',kwargs={'slug': self.kwargs.get('slug'),'elnamo':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group= get_object_or_404(EGroup,slug=self.kwargs.get('slug'))

        try:
            InGroup.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'warning already a member!')
        else:
            messages.success(self.request,'Your are now a member')
        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):


    def get_redirect_url(self,*args,**kwargs):
        return reverse('experiment:single1',kwargs={'slug':self.kwargs.get('slug'),'elnamo':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = models.InGroup.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.InGroup.DoesNotExist:
            messages.warning(self.request,'sorry you arent in this group!')

        else:
            membership.delete()
            messages.success(self.request,'you have left the group')

        return super().get(request,*args,**kwargs)

class BecomeJudge(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('experiment:single1',kwargs={'slug': self.kwargs.get('slug'),'elnamo':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group= get_object_or_404(EGroup,slug=self.kwargs.get('slug'))
        person=self.kwargs.get('elnamo')
        try:
            if person != group.slug:
                IsJudge.objects.create(judge1=User.objects.get(email=self.kwargs.get('elnamo')),courtroom=group)
        except IntegrityError:
            messages.warning(self.request,'warning already a member!')
        else:
            messages.success(self.request,'Your are now a judge')
        return super().get(request,*args,**kwargs)

class UnJudge(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('experiment:single1',kwargs={'slug':self.kwargs.get('slug'),'elnamo':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            courtroomjudge = models.IsJudge.objects.filter(
                judge1=User.objects.get(email=self.kwargs.get('elnamo')),
                courtroom__slug=self.kwargs.get('slug')
            ).get()
        except models.IsJudge.DoesNotExist:
            messages.warning(self.request,'sorry you arent in this group!')
        else:
            courtroomjudge.delete()
            messages.success(self.request,'you have left the group')

        return super().get(request,*args,**kwargs)

antonspro/experiment/templates/experiment/egroup_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'antonspro/css/goldexp.css' %}">

  </head>

  <body>
{% block content %}

<div id=navbar></div>

<a href="{% url 'experiment:all1' %}"><div id=navhome></div></a>
<a href="{% url 'experiment:create1' %}"><div id=createnav></div></a>
<div id=dice></div>
<a href="{% url 'buy' %}"><div id=getgoldnav></div></a>
<a href="{% url 'experiment:myrooms' %}"><div id=myroomsnav></div></a>



<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

</body>

</html>

antonspro/experiment/templates/experiment/egroup_detail.html
{% extends 'experiment/egroup_base.html' %}
{% load static %}
{% block pregroup %}
    <link rel="stylesheet" href="{% static 'antonspro/css/goldexp.css' %}">

<h1>{{name}}</h1>
<h2>{{name.description}}</h2>
{% if name.judge.count == 0 %}
  {% for user in name.members1.all %}
    <a href="{% url 'experiment:bjudge1' slug=name.slug elnamo=user %}"
      class="btn btn-lg btn-fill btn-warning"><span
      class='glyphicon glyphicon-ok-circle'></span>make {{user}} the judge</a>
    <p></p>
  {% endfor %}
{% endif %}
{% if user in name.judge.all %}
<a href="{% url 'experiment:unjudge1' slug=name.slug elnamo=user %}"
  class="btn btn-lg btn-fill btn-warning"><span
  class='glyphicon glyphicon-ok-circle'></span>Step down from judgeship</a>
{% endif %}

<div id="userinfo">
  your gold is:<div id=numb>{{user.gold}}</div>
  <p></p>
  <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" name="button">Submit</button>
  </form>
  <p></p>
  {% if user not in name.members1.all %}
  <a href="{% url 'experiment:join1' slug=name.slug elnamo=name.slug  %}"
      class="btn btn-lg btn-fill btn-warning"><span
      class='glyphicon glyphicon-ok-circle'></span>Join room</a>
  {% endif %}
{% if user in name.members1.all %}
  <a href="{% url 'experiment:leave1' slug=name.slug elnamo=name.slug %}"
      class="btn btn-lg btn-fill btn-warning"><span
      class='glyphicon glyphicon-remove-circle'></span>Leave room</a>
{% endif %}
</div>

<div id="roominfo">
  Gold in room:<div id=numb>{{name.goldinroom}}</div>
  Members in room: {{name.members1.count}}
  {% for user in name.judge.all %}
    <p>{{user.username}} Is The Judge</p>
  {% endfor %}
</div>

<div id="forjudge">
  {% for person in name.judge.all %}
    {% if user == person %}
      {% for user in name.members1.all %}
        <form method="POST">
          {% csrf_token %}
          {{ user.username }}:
          {{ form3 }}
          <button type="submit" name="name" value="{{ user.username}}">Assign Gold</button>
        </form>
      {% endfor %}
    {% endif %}
  {% endfor %}
</div>



{% endblock %}

antonspro/experiment/templates/experiment/egroup_form.html
{% load bootstrap3 %}



<h4>create a new group</h4>

  <form action="{% url 'experiment:create1' %}" method="post" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn large" value="Create Group">
  </form>

antonspro/experiment/templates/experiment/egroup_list.html
{% extends 'experiment/egroup_base.html' %}
{% load static %}



{% block group_content %}
<link rel="stylesheet" href="{% static 'antonspro/css/goldexp.css' %}">


        {% for group in object_list %}
          <a href="{% url 'experiment:single1' slug=group.slug elnamo=group.slug %}">
            <div id=rooms>
              <div id=words>{{group.name}}</div>
              <div>{{group.description_html|safe}}</div>
            </div>
          </a>

        {% endfor %}

{% endblock %}

antonspro/experiment/templates/experiment/first.html
{% extends 'experiment/egroup_base.html' %}
{% load static %}
{% block pregroup %}

Rooms you are currently a part of:

{% for room in object_list %}
  <a href="{% url 'experiment:single1' slug=room.group.slug elnamo=room.group.slug %}">
    <div id=rooms>
      <div id=words>{{room.group}}</div>
    </div>
  </a>
{% endfor %}

{% endblock %}