antonspro/about/urls.py
from django.conf.urls import url
from . import views


app_name='about'

urlpatterns= [
    url(r'aboutSu$',views.SuAbout.as_view(),name='aboutsu'),
    url(r'^general/$',views.GenAbout.as_view(),name='general'),
    url(r'^planet/$',views.PlanetAbout.as_view(),name='aboutpe')
]

antonspro/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup'),
]

antonspro/adventure/urls.py
from . import views
from django.conf.urls import url

app_name='adventure'

urlpatterns= [
    url(r'^$',views.start1.as_view(),name='start1'),
    url(r'^A2/$',views.A2.as_view(),name='A2'),
    ]

antonspro/antonspro/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Home/$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^$',views.MasterPage.as_view(),name='masterpage'),
    url(r'^sudoku/',include('sudoku.urls',namespace='sudoku')),
    url(r'^about/',include('about.urls',namespace='about')),
    url(r'^experiment/',include('experiment.urls',namespace='experiment')),
    url(r'^buy/$',views.BuyPage.as_view(),name='buy'),
    url(r'^magicclub/',include('magicclub.urls',namespace='magicclub')),
    url(r'^adventure/',include('adventure.urls',namespace='adventure')),
]

antonspro/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns= [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'new/$',views.CreatePost.as_view(),name='create'),
    url(r'by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete')
]

antonspro/sudoku/urls.py
from django.conf.urls import url
from . import views


app_name='sudoku'

urlpatterns= [
    url(r'^$',views.SudokuSolve.as_view(),name='sudoku'),
    url(r'fill/$',views.FillBoard.as_view(),name='FillBoard'),
    # url(r'^search/',views.solution.as_view(),name='solution')
]

antonspro/about/models.py
from django.db import models

# Create your models here.

antonspro/about/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class GenAbout(TemplateView):
    template_name= 'about/generalabout.html'

class SuAbout(TemplateView):
    template_name= 'about/aboutsudoku.html'

class PlanetAbout(TemplateView):
    template_name= 'about/planetabout.html'

antonspro/templates/Buy.html
{% extends 'experiment/egroup_base.html' %}
{% load static %}


{% block pregroup %}

<div id=yourgold>Your Gold: {{ user.gold }}</div>

<div id=buyername>, {{ user.username }}</div>

    <form method="POST">
        {% csrf_token %}
        <div id=form>{{ form.as_p }}</div>
        <button type="submit" name="button" id=buybutton>Buy Now</button>
    </form>

  <div id=submitbuy></div>


{% endblock %}

antonspro/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'antonspro/css/sudokurelated.css' %}">
    <script src="http://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id="bignav">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}" id="homenav"></a>
        <a href="{% url 'about:general' %}" class="navbar-brand mynav" id="aboutnav"></a>
        <ul class="nav navbar-nav navbar-right">

        </ul>
      </div>
    </nav>

  <div class="list-group" id="sidenav">
    <button type="button" class="list-group-item">General</button>
    <button type="button" class="list-group-item">Planet Express app</button>
    <button type="button" class="list-group-item">Sudoku puzzle solver</button>
  </div>
  {{ 1.as_p }}







    <script type="text/javascript" src="{% static 'antonspro/js/master.js' %}">
    </script>
  </body>
</html>

antonspro/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'antonspro/css/master.css' %}">

  </head>
  <body>

    <nav class="navbar mynav" role='navigation' id='navbar'>
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Express Pickup</a>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <!-- <li><a href="{% url 'posts:create' %}">Post</a></li>
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'groups:create' %}">Create Group</a></li> -->
            <a href="{% url 'accounts:logout' %}">Log Out </a>
          {% else %}
            <li><a href="{% url 'accounts:login' %}">Log In </a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
          {% if perms.User.can_drive %}
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

  </body>
  <script type="text/javascript" src="{% static 'antonspro/js/master.js' %}">
  </script>
</html>

antonspro/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'antonspro/css/sudokurelated.css' %}">
      <script
    			  src="http://code.jquery.com/jquery-3.5.1.js"
    			  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    			  crossorigin="anonymous"></script>


  </head>


  <body>
    <nav class="navbar mynav" role='navigation' id="bignav">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'masterpage' %}" id="homenav"></a>
        <a href="{% url 'about:general' %}" class="navbar-brand mynav" id="aboutnav"></a>
        <ul class="nav navbar-nav navbar-right">
        </ul>
      </div>
    </nav>

      <h1> Hello, thanks for visiting!</h1>

    <a href="{% url 'home' %}">
      <div id="drivediv" class="drivediv">
        <p>planet express form</p>
        <div class="drivemove" id="drivemove"></div>
      </div>
    </a>

    <a href="{% url 'sudoku:FillBoard' %}" index='Sulink'>
      <div id="sudiv" class="sudiv">
        <p>Sudoku board solver</p>
        <div class="move" id="move"></div>
      </div>
    </a>

    <a href="{% url 'magicclub:home' %}">
      <div id="magicdiv" class="magicdiv">
        <p>  Magic Club Thun</p>
        <div class="magicmove" id="magicmove"></div>
      </div>
    </a>

    <a href="{% url 'experiment:all1' %}">
      <div id="gamblediv" class="gamblediv">
        <p>Gamble</p>
        <div class="gamblemove" id="gamblemove"></div>
      </div>
    </a>


      <div id="adventurediv" class="adventurediv">
        <p>Adventure Time</p>
        <div class="noclass" id="noid"></div>
      </div>

      <div id="hero"></div>

      <div id="warpportal" class="warpportal"></div>



    <div class="jet" id="jet"></div>




      <script type="text/javascript" src="{% static 'antonspro/js/master.js' %}">
      </script>
  </body>

  <a href="{% url 'adventure:start1' %}">adventure time</a>

</html>

antonspro/templates/profiletype.html
{% extends 'base.html' %}

{% block content %}


<h1>Your request has been submitted.</h1>
<h2>you will recieve a notification as soon as your request has been picked-up</h2>

  {% endblock %}

antonspro/templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>you are now logged in</h1>

{% endblock %}

antonspro/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Logged out successfully</h1>

{% endblock %}