antonspro/about/urls.py
from django.conf.urls import url
from . import views


app_name='about'

urlpatterns= [
    url(r'aboutSu$',views.SuAbout.as_view(),name='aboutsu'),
    url(r'^general/$',views.GenAbout.as_view(),name='general'),
    url(r'^planet/$',views.PlanetAbout.as_view(),name='aboutpe')
]

antonspro/antonspro/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Home/$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^$',views.MasterPage.as_view(),name='masterpage'),
    url(r'^sudoku/',include('sudoku.urls',namespace='sudoku')),
    url(r'^about/',include('about.urls',namespace='about')),
    url(r'^experiment/',include('experiment.urls',namespace='experiment')),
    url(r'^buy/$',views.BuyPage.as_view(),name='buy'),
    url(r'^magicclub/',include('magicclub.urls',namespace='magicclub')),
    url(r'^adventure/',include('adventure.urls',namespace='adventure')),
]

antonspro/magicclub/urls.py
from django.conf.urls import url

from . import views

app_name='magicclub'

urlpatterns= [
    url(r'^$',views.Homepage.as_view(),name='home'),
    url(r'tournament/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='swiss'),
    url(r'pairings/(?P<slug>[-\w]+)/$',views.PairGroup.as_view(),name='pairings'),
    url(r'new/$',views.CreateGroup.as_view(),name='create'),
    url(r'all/$',views.ListGroups.as_view(),name='all'),
    url(r'standings/(?P<slug>[-\w]+)/$',views.StandingsGroup.as_view(),name='standings'),
    # url(r'by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    # url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    # url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete')
]

antonspro/magicclub/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import pickle

# Create your models here.

class Tournament(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html= models.TextField(editable=False,default='',blank=True)
    players= []
    table=[]
    drop=[]
    tempplayers=[]
    clubmembers=[]
    round=0

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug= slugify(self.name)

        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('magicclub:swiss',kwargs={'slug':self.slug})

    class Meta:
        ordering= ['name']

antonspro/magicclub/forms.py
from django import forms
from . import views
from accounts.models import Account
from django.shortcuts import render
from django.db import models


class NameForm(forms.Form):
    playername= forms.CharField(max_length=20,min_length=1,required=False)

class DropForm(forms.Form):
    drop= forms.CharField(max_length=20,min_length=1,required=False)

class ClubForm(forms.Form):
    clubm= forms.CharField(max_length=20,min_length=1,required=False)

class PairNow(forms.Form):
    round= forms.DecimalField(max_value=None,min_value=0,max_digits=6,decimal_places=2,initial=0,label='',required=False)

class APoints(forms.Form):
    p1= forms.DecimalField(max_value=2,min_value=0,max_digits=1,decimal_places=0,initial=0,label='',required="False")
    p2= forms.DecimalField(max_value=2,min_value=0,max_digits=1,decimal_places=0,initial=0,label='',required="False")

class SaveForm(forms.Form):
    update1= forms.DecimalField(max_value=None,min_value=1,max_digits=6,decimal_places=2,initial=0,label='',required=False)

class LoadForm(forms.Form):
    load1= forms.DecimalField(max_value=None,min_value=1,max_digits=6,decimal_places=2,initial=0,label='',required=False)

class ClearForm(forms.Form):
    clearit= forms.DecimalField(max_value=None,min_value=1,max_digits=6,decimal_places=2,initial=0,label='',required=False)

class ClubMemberPoints(forms.Form):
    format= forms.CharField(max_length=20,min_length=1,required=False)

antonspro/magicclub/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from magicclub.models import Tournament
from django.urls import reverse
from django.views import generic
from .forms import NameForm,PairNow,APoints,DropForm,ClubForm,SaveForm,LoadForm,ClearForm,ClubMemberPoints
from django.shortcuts import get_object_or_404
import random
import operator
from random import shuffle
from operator import itemgetter, attrgetter, methodcaller
import pickle

# Create your views here.


class Homepage(TemplateView):
    template_name= 'magicclub/home.html'

class CreateGroup(generic.CreateView):
    fields=('name','description')
    model= Tournament

class SingleGroup(generic.DetailView):
    template_name = 'magicclub/tournament_detail.html'
    model=Tournament

    def get(self, request, slug):
        model=Tournament
        group= get_object_or_404(Tournament,slug=self.kwargs.get('slug'))
        form1 = NameForm()
        form2= DropForm()
        form3= ClubForm()
        form4= SaveForm()
        form5= LoadForm()
        form6= ClearForm()


        dill1=open('magicclub/tournamentdata/clubmembers.pickle','rb')
        clubpeeps=pickle.load(dill1)
        dill1.close()

        if len(group.clubmembers)==0:
            for person in clubpeeps:
                group.clubmembers.append(person[0])



        args = {'form1':form1,'group':group,'form2':form2,'form4':form4,'form5':form5,'form6':form6}
        return render(request,self.template_name,args)


    def post(self, request,slug):
        model=Tournament
        form1 = NameForm(request.POST)
        form2= DropForm(request.POST)
        form3= ClubForm(request.POST)
        form4= SaveForm(request.POST)
        form5= LoadForm(request.POST)
        form6= ClearForm(request.POST)
        group= get_object_or_404(Tournament,slug=self.kwargs.get('slug'))
        clubpeeps= group.clubmembers



        if form1.is_valid():
            if form1.cleaned_data["playername"]:
                name = form1.cleaned_data["playername"]

                if name not in group.tempplayers:
                    group.tempplayers.append(name)
                    group.players.append([name,0,0,0,[]])
                    group.save()
                else:
                    group.tempplayers.remove(name)
                    for person in group.players:
                        if name==person[0]:
                            group.players.remove(person)

        if form2.is_valid():
            if form2.cleaned_data["drop"]:
                todrop= form2.cleaned_data["drop"]
                for name in group.players:
                    if name[0].lower() == todrop.lower():
                        group.tempplayers.remove(name[0])
                        group.players.remove(name)
                        group.drop.append(name)
                        group.save()


        if form4.is_valid():
            if form4.cleaned_data["update1"]:
                try:
                    dill1=open('magicclub/tournamentdata/{}.pickle'.format(group.name),'ab')
                    pickle.dump(group.players,dill)
                    dill1.close()
                except:
                    dill1= open('magicclub/tournamentdata/{}.pickle'.format(group.name),'wb')
                    pickle.dump(group.players,dill1)
                    dill1.close()

        if form5.is_valid():
            if form5.cleaned_data["load1"]:
                group.players.clear()
                pickedin=open('magicclub/tournamentdata/{}.pickle'.format(group.name),'rb')
                picklelist=pickle.load(pickedin)
                for person in picklelist:
                    group.players.append(person)
                    group.save()
                pickedin.close()

        if form6.is_valid():
            if form6.cleaned_data["clearit"]:
                group.players.clear()
                group.drop.clear()
                group.tempplayers.clear()
                group.save()



        clubboy=request.POST.get('name')
        if str(clubboy) != 'None':
            group.players.append([clubboy,0,0,0,[]])
            group.tempplayers.append(clubboy)
            group.save()


        args = {'form1':form1,'group':group,'form2':form2,'form3':form3,'form4':form4,'form5':form5,'form6':form6}
        return render(request, self.template_name,args)

class PairGroup(generic.DetailView):
    template_name = 'magicclub/pairings.html'
    model=Tournament

    def get(self, request, slug):
        model=Tournament
        group= get_object_or_404(Tournament,slug=self.kwargs.get('slug'))
        form1= PairNow()
        form2= APoints()
        table=group.table
        args = {'group':group,'form1':form1,'table':table,'form2':form2}
        return render(request,self.template_name,args)

    def post(self, request, slug):
        model=Tournament
        form1= PairNow(request.POST)
        form2= APoints(request.POST)
        group= get_object_or_404(Tournament,slug=self.kwargs.get('slug'))
        playerpoints=group.players
        nlist=[]
        ulist=[]
        bye=[]
        table=group.table
        if form1.is_valid():
            if len(table)==0:
                random.shuffle(playerpoints)
                playerpoints=sorted(playerpoints,key=itemgetter(1), reverse=False)

                if len(playerpoints)%2==1: #bye handling, will have to edit later
                    for person in playerpoints:
                        if 'bye' in person[4]:
                            None
                        else:
                            bye.append(person)
                            playerpoints.remove(person)
                            for name in group.players:
                                if name[0]==bye[0][0]:
                                    name[1]=name[1]+3
                                    name[2]=name[2]+2
                                    name[4].append('bye')
                            break

                tablenum=1
                templist=[]
                playerpoints=sorted(playerpoints,key=itemgetter(1), reverse=True)

                while len(playerpoints)>0: #pairings
                    if playerpoints[1][0] in playerpoints[0][4]:
                        if len(playerpoints)==2:
                            templist.append([playerpoints[0],playerpoints[1]])
                            table.append([playerpoints[0][0],playerpoints[1][0],'table '+str(tablenum)])
                            playerpoints.pop(0)
                            playerpoints.pop(0)
                            tablenum+=1

                        else:
                            for n in playerpoints[1::]:
                                if n[0] not in playerpoints[0][4]:
                                    templist.append([playerpoints[0],n])
                                    table.append([playerpoints[0][0],n[0],'table '+str(tablenum)])
                                    playerpoints.remove(n)
                                    playerpoints.pop(0)
                                    tablenum+=1
                                    break
                    else:
                        templist.append([playerpoints[0],playerpoints[1]])
                        table.append([playerpoints[0][0],playerpoints[1][0],'table '+str(tablenum)])
                        playerpoints.pop(0)
                        playerpoints.pop(0)
                        tablenum+=1

                for n in templist:
                    for g in n:
                        playerpoints.append(g)



        if form2.is_valid():
            pone = int(form2.cleaned_data["p1"])
            ptwo = int(form2.cleaned_data["p2"])
            table1=request.POST.get('name')
            for thing in table:
                if thing[2]==table1:
                    for name in group.players:
                        if name[0]==thing[0]:
                            if pone>ptwo:
                                name[1]=name[1]+3
                            name[2]=name[2]+pone
                            name[3]=name[3]+ptwo
                            name[4].append(thing[1])
                            if pone==ptwo:
                                name[1]=name[1]+1
                            group.save()

                    for name in group.players:
                        if name[0]==thing[1]:
                            if ptwo>pone:
                                name[1]=name[1]+3
                            name[2]=name[2]+ptwo
                            name[3]=name[3]+pone
                            name[4].append(thing[0])
                            if pone==ptwo:
                                name[1]=name[1]+1
                            group.save()
                    group.table.remove(thing)





        args = {'group':group,'table':table,'form2':form2,'bye':bye}
        return render(request,self.template_name,args)


class ListGroups(generic.ListView):
    model = Tournament

class StandingsGroup(generic.DetailView):
    template_name = 'magicclub/standings.html'
    model=Tournament

    def get(self, request, slug):
        model=Tournament
        group= get_object_or_404(Tournament,slug=self.kwargs.get('slug'))
        playerpoints=group.players
        recordclub=ClubMemberPoints()

        # global droplist
        standings1=[]
        for name in group.drop:
            playerpoints.append(name)
        for n in playerpoints:
            breakers=[0,0,0]
            try:
                if n[2]/(n[2]+n[3])>32:
                    breakers[1]=n[2]/(n[2]+n[3]) #T2
                else:
                    breakers[1]=33
            except:
                ZeroDivisionError
                breakers[1]=0
            for player in n[4]:
                for sameplayer in playerpoints:
                    if sameplayer[0]==player:
                        breakers[0]=breakers[0]+((sameplayer[1]/3)/len(sameplayer[4])) #T1 the 1 has to be replaced by number of rounds

antonspro/magicclub/templates/magicclub/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'antonspro/css/magicclub.css' %}">
    <script
          src="http://code.jquery.com/jquery-3.5.1.js"
          integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
          crossorigin="anonymous"></script>
  </head>
  <body>

    <div id=navbar>
      <a href="{% url 'magicclub:home' %}"><div id=homenav ></div></a>
      <a href="{% url 'magicclub:all' %}"><div id=allnav></div></a>
      <a href="{% url 'magicclub:create' %}"><div id=createnav></div></a>
    </div>

    <div id="front" class="front"></div>
    <div id="back" class="back"></div>


    <script type="text/javascript" src="{% static 'antonspro/js/magicclub.js' %}">
    </script>
  </body>
</html>

antonspro/magicclub/templates/magicclub/pairings.html
{% extends 'magicclub/tournament_base.html' %}

{% block pregroup %}

<a href="{% url 'magicclub:swiss' slug=group.slug %}">Back to adding players</a>
<a href="{% url 'magicclub:standings' slug=group.slug %}">To standings</a>

<form method="POST">
    {% csrf_token %}
    {{ form1.as_p }}
    <button type="submit" name="button">Submit</button>
</form>

{% for group in table %}
  <form method="POST" id="{% cycle 'odd' 'even' %}">
    {% csrf_token %}
    {{group.0}} {{form2.p1}} vs {{group.1}} {{form2.p2}} on {{group.2}}
    <button type="submit" name="name" value="{{group.2}}">Record points</button>
  </form>
{% endfor %}
{{bye}} has the bye

{% endblock %}

antonspro/magicclub/templates/magicclub/standings.html
{% extends 'magicclub/tournament_base.html' %}

{% block pregroup %}

<a href="{% url 'magicclub:pairings' slug=group.slug %}">To pairings</a>
<a href="{% url 'magicclub:swiss' slug=group.slug %}">Back to adding players</a>
<p></p>

<div id=standingdiv>
  <div id=word1>Place</div><div id=word1>Name</div><div id=word1>Wins</div><div id=word1>T1</div><div id=word1>T2</div><div id=word1>T3</div>
</div>

{% for item in standings1 %}
  <div id=standingdiv>
    <div id=word1>{{ forloop.counter}}</div><div id=word1>{{ item.0 }}</div><div id=word1>{{ item.1 }}</div><div id=word1>{{ item.2 }}</div><div id=word1>{{ item.3 }}</div><div id=word1>{{ item.4 }}</div>
  </div>
{% endfor %}



<div id=memberpoints>
Save Club members points:
<form method="POST">
    {% csrf_token %}
    {{ recordclub.as_p }}
    <button type="submit" name="button">Submit</button>
</form>
</div>




{% endblock %}

antonspro/magicclub/templates/magicclub/tournament_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'antonspro/css/magicclub.css' %}">
  </head>
  <body>

    {% block content %}

    <div id=navbar>
      <a href="{% url 'magicclub:home' %}"><div id=homenav ></div></a>
      <a href="{% url 'magicclub:all' %}"><div id=allnav></div></a>
      <a href="{% url 'magicclub:create' %}"><div id=createnav></div></a>
    </div>




    <div class="container">
      <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
      </div>
    </div>

    {% endblock %}

  </body>
</html>

antonspro/magicclub/templates/magicclub/tournament_detail.html
{% extends 'magicclub/tournament_base.html' %}

{% block pregroup %}
Players: {{ group.players|length }} 
<div id=addplayers>
  <div id=contents>
  <form method="POST">
      {% csrf_token %}
      {{ form1.as_p }}
      <button type="submit" name="button">add player</button>
  </form>
  </div>

{% for person in group.players %}
  {{ person.0 }}
{% endfor %}

</div>

<div id=drop>
<form method="POST">
    {% csrf_token %}
    {{ form2.as_p }}
    <button type="submit" name="button">Drop player</button>
</form>
</div>

<div id=clubmembers>
{% for playuh in group.clubmembers %}
  {% if playuh in group.tempplayers %}
    {% else %}
      <form method="POST" id='one'>
          {% csrf_token %}
          <button type="submit" name="name" value="{{playuh}}" id=clubmembernames>{{ playuh }}</button>
      </form>
  {% endif %}
{% endfor %}
</div>

<div id=save>
<form method="POST">
    {% csrf_token %}
    {{ form4.as_p }}
    <button type="submit" name="button">Save progress</button>
</form>
</div>

<div id=load>
  <form method="POST">
      {% csrf_token %}
      {{ form5.as_p }}
      <button type="submit" name="button">Load last save</button>
  </form>
</div>

<div id=clear>
  <form method="POST">
      {% csrf_token %}
      {{ form6.as_p }}
      <button type="submit" name="button">Clear Player-list</button>
  </form>
</div>


<div id=pairstand>
<a href="{% url 'magicclub:pairings' slug=group.slug %}">To pairings</a> |
<a href="{% url 'magicclub:standings' slug=group.slug %}">To standings</a>
</div>



{% endblock %}

antonspro/magicclub/templates/magicclub/tournament_form.html
{% load bootstrap3 %}

    <form action="{% url 'magicclub:create' %}" method="post" id="groupForm">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary btn large" value="Create new tournament">
    </form>

antonspro/magicclub/templates/magicclub/tournament_list.html
{% extends 'magicclub/tournament_base.html' %}


{% block group_content %}

Recent Events:

{% for group in object_list %}
  <a href="{% url 'magicclub:swiss' slug=group.slug %}">
    <div id=rooms>
      <div id=words>{{group.name}}</div>
      <div>{{group.description_html|safe}}</div>
    </div>
  </a>
{% endfor %}

{% endblock %}